(() => {
const app=document.getElementById("app");
const old=JSON.parse(localStorage.getItem("mindfuel")||"{}");
const s={xp:Number(old.xp||0),history:Array.isArray(old.history)?old.history:[],bookmarks:Array.isArray(old.bookmarks)?old.bookmarks:[],profile:old.profile||{name:"Neha"}};
const save=()=>localStorage.setItem("mindfuel",JSON.stringify(s));
const toast=t=>{document.querySelectorAll(".toast").forEach(x=>x.remove());const e=document.createElement("div");e.className="toast";e.textContent=t;document.body.appendChild(e);setTimeout(()=>e.remove(),1500)};
const page=(html,cls="")=>{app.innerHTML=`<main class="page ${cls}">${html}</main>`;return app.querySelector(".page")};
const nav=(active)=>{const p=app.querySelector(".page"),n=document.createElement("nav");n.className="nav";[["⌂","Home","home"],["🧠","Quiz","quiz"],["Aa","Words","words"],["☰","Menu","drawer"]].forEach(([i,l,k])=>{const b=document.createElement("button");b.innerHTML=`${i}<br>${l}`;if(active===k)b.className="active";b.onclick=()=>go(k);n.appendChild(b)});p.appendChild(n)};
const go=k=>({home,quiz,words,hr,india,world,progress,achievements,history,bookmarks,settings,about,drawer}[k]||home)();

function splash(){const p=page(`<div class="brand"><h1>MindFuel</h1><p>Your daily mental workout<br>for a smarter, sharper you.</p></div><div class="credit">Created with ❤️ by Neha Hemant Nevrekar</div><button class="begin">LET'S BEGIN</button>`,"splash");p.querySelector(".begin").onclick=home}
function home(){const p=page(`<header class="header"><button class="icon" id="menu">☰</button><div class="title">MindFuel</div><button class="icon" id="profile">●</button></header><div class="hello">Hello, ${s.profile.name||"Neha"} 👋</div><div class="quote">A little learning every day adds up to big dreams.<span class="heart">♥</span></div><div class="grid"><button class="card wide" data-go="quiz"><span class="emoji">🧠</span><strong>Brain Challenge</strong><small>Fresh questions every time you play</small></button><button class="card" data-go="words"><span class="emoji">📚</span><strong>New Word</strong><small>Meaning, example & synonyms</small></button><button class="card" data-go="hr"><span class="emoji">💼</span><strong>HR Radar</strong><small>Workplace insights</small></button><button class="card" data-go="india"><span class="emoji">🇮🇳</span><strong>India Now</strong><small>Important updates</small></button><button class="card" data-go="world"><span class="emoji">🌍</span><strong>World Now</strong><small>Global learning</small></button><button class="card" data-go="progress"><span class="emoji">📈</span><strong>My Progress</strong><small>${s.xp} XP</small></button></div><div class="footer">Created with ❤️ by Neha Hemant Nevrekar</div>`,"home");p.querySelector("#menu").onclick=drawer;p.querySelector("#profile").onclick=()=>toast(s.profile.name||"Neha");p.querySelectorAll("[data-go]").forEach(b=>b.onclick=()=>go(b.dataset.go));nav("home")}

const qs=[
["Which skill is most useful for solving a new problem?",["Critical thinking","Guessing","Ignoring details","Avoiding questions"],0],
["What does HRBP stand for?",["Human Resources Business Partner","Human Retail Business Plan","Hiring Role Business Process","Human Relations Benefit Policy"],0],
["Which habit best improves vocabulary?",["Learning and using new words","Never reading","Repeating one word","Skipping examples"],0],
["Which approach helps you learn consistently?",["Small daily practice","Studying once a month","Avoiding revision","Waiting for motivation"],0],
["Which behaviour supports good teamwork?",["Active listening","Ignoring others","Avoiding feedback","Keeping information to yourself"],0],
["What is a useful way to remember something new?",["Connect it to an example","Never revisit it","Skip practice","Only read it once"],0]
];
function quiz(){let idx=Math.floor(Math.random()*qs.length),answered=false;const p=page(`<div class="panel"><button class="back" id="back">‹ Back</button><div class="panelbox"><h1>🧠 Brain Challenge</h1><p class="muted">Fresh questions • ⚡ ${s.xp} XP</p><div id="q"></div></div></div>`);p.querySelector("#back").onclick=home;function render(){answered=false;const q=qs[idx];p.querySelector("#q").innerHTML=`<span class="muted">Daily Quiz</span><h2>${q[0]}</h2><div>${q[1].map((x,i)=>`<button class="option" data-i="${i}">${x}</button>`).join("")}</div><button class="primary" id="next">Next Question</button>`;p.querySelectorAll(".option").forEach(b=>b.onclick=()=>{if(answered)return;answered=true;const ok=+b.dataset.i===q[2];b.classList.add(ok?"correct":"wrong");s.history.push({question:q[0],correct:ok,date:new Date().toISOString()});if(ok){s.xp+=10;toast("+10 XP")}else toast("Keep learning!");save()});p.querySelector("#next").onclick=()=>{idx=Math.floor(Math.random()*qs.length);render()}}render();nav("quiz")}

const words=[
["Insightful","showing a clear understanding","She gave an insightful answer during the discussion.","perceptive · thoughtful · discerning"],
["Resilient","able to recover quickly from difficulty","She remained resilient through the change.","strong · adaptable · enduring"],
["Curious","eager to know or learn something","A curious mind keeps growing.","inquisitive · interested · eager"],
["Articulate","able to express ideas clearly","He was articulate during the presentation.","eloquent · expressive · clear"],
["Adaptable","able to adjust to new conditions","An adaptable learner welcomes change.","flexible · versatile · adjustable"],
["Meticulous","very careful and precise","She was meticulous while checking the report.","careful · thorough · precise"],
["Empathy","the ability to understand another person's feelings","Empathy helps create stronger connections.","understanding · compassion · sensitivity"]
];
function words(){const d=Math.floor(Date.now()/86400000)%words.length,w=words[d],saved=s.bookmarks.includes(w[0]);const p=page(`<div class="panel"><button class="back" id="back">‹ Back</button><div class="panelbox"><h1>📚 English Lab</h1><p class="muted">NEW WORD OF THE DAY</p><h2>${w[0]}</h2><p><b>Meaning:</b> ${w[1]}.</p><p><b>Example:</b> ${w[2]}</p><p><b>Synonyms:</b> ${w[3]}</p><div class="word-nav"><button id="prev">‹ Previous</button><button id="nextword">Next ›</button></div><button class="primary" id="bookmark">${saved?"★ Bookmarked":"☆ Bookmark Word"}</button><button class="primary" id="history">View Quiz History</button></div></div>`);p.querySelector("#back").onclick=home;p.querySelector("#bookmark").onclick=()=>{if(s.bookmarks.includes(w[0]))s.bookmarks=s.bookmarks.filter(x=>x!==w[0]);else s.bookmarks.push(w[0]);save();p.querySelector("#bookmark").textContent=s.bookmarks.includes(w[0])?"★ Bookmarked":"☆ Bookmark Word"};p.querySelector("#nextword").onclick=()=>toast("Tomorrow's word will be a fresh word");p.querySelector("#prev").onclick=()=>toast("Explore your saved words in Bookmarks");p.querySelector("#history").onclick=history;nav("words")}

function simple(title,emoji,text){const p=page(`<div class="panel"><button class="back" id="back">‹ Back</button><div class="panelbox"><h1>${emoji} ${title}</h1><p class="muted">${text}</p></div></div>`);p.querySelector("#back").onclick=home}
function hr(){simple("HR Radar","💼","People, workplace and HR insights at a glance.");nav("")}
function india(){simple("India Now","🇮🇳","Stay informed with important India updates.");nav("")}
function world(){simple("World Now","🌍","Explore global developments and why they matter.");nav("")}
function progress(){simple("My Progress","📈",`${s.xp} XP earned • ${s.history.length} quiz attempts • ${s.history.filter(x=>x.correct).length} correct answers.`);nav("")}
function achievements(){simple("Achievements","🏆",s.xp>=100?"🏆 100 XP milestone unlocked!":"Keep learning to reach 100 XP.");nav("")}
function history(){const p=page(`<div class="panel"><button class="back" id="back">‹ Back</button><div class="panelbox"><h1>🕘 Quiz History</h1><div>${s.history.length?s.history.slice().reverse().map(x=>`<p>${x.correct?"✅":"❌"} ${x.question}<br><small class="muted">${new Date(x.date).toLocaleDateString()}</small></p>`).join(""):"<p class='muted'>No quiz history yet.</p>"}</div></div></div>`);p.querySelector("#back").onclick=home;nav("")}
function bookmarks(){simple("Bookmarks","🔖",s.bookmarks.length?s.bookmarks.join(" • "):"No bookmarked words yet.");nav("")}
function settings(){simple("Settings","⚙️","Your profile and MindFuel preferences.");nav("")}
function about(){simple("About MindFuel","💜","A little learning every day adds up to big dreams. Created with ❤️ by Neha Hemant Nevrekar.");nav("")}
function drawer(){app.innerHTML=`<aside class="drawer"><button class="back" id="close">✕ Close</button><h1>MindFuel</h1><p>Learn a little. Grow a lot.</p>${[["Home",home],["Brain Challenge",quiz],["New Word",words],["HR Radar",hr],["India Now",india],["World Now",world],["My Progress",progress],["Achievements",achievements],["Quiz History",history],["Bookmarks",bookmarks],["Settings",settings],["About MindFuel",about]].map(([x],i)=>`<button class="item" data-i="${i}">${x}</button>`).join("")}</aside>`;const f=[home,quiz,words,hr,india,world,progress,achievements,history,bookmarks,settings,about];app.querySelector("#close").onclick=home;app.querySelectorAll(".item").forEach((b,i)=>b.onclick=f[i])}
splash();
})();